### ISSUE TITLE
how include sdk in my android project.

### ISSUE THREAD

**Issue by danielcheril** [danielvictor/helpshift-android-sdk-examples#4]
Hi, 

 This is daniel. You gave a android project. In that demo need to referencing sdk by the following way.

Add reference of the Helpshift SDK to your project :

In the Package Explorer, right-click your project and select Properties.
In the Properties window, select the “Android” properties group at left and locate the Library properties at right.
Click Add to open the Project Selection dialog. From the list of available library projects, select Helpshift SDK and click OK.
                instead of that, include sdk in my project. 

            Because we previously included sdks in project, like facebook, twitter, mixpanel, accapella, and so, on. How include your sdk in our Project. 

Help me.

Thanks in advance.

Regards
Daniel Raja Singh V.M.

**Comment by danielvictor** [comment]
Hi,

Please send all support queries to support@helpshift.com so we can monitor and answer them in a timely fashion to avoid delays.
