### ISSUE TITLE
How to customize theme while using gradle

### ISSUE THREAD

**Issue by BugsBunnyBR** [danielvictor/helpshift-android-sdk-examples#5]
Hi, I am using gradle and would like to know if there is a way to customize the HelpShift Activities.

**Comment by dnivra26** [comment]
+1

**Comment by danmidou** [comment]
Hi, 

Please refer to the documentation for the Helpshift Android SDK found here -
https://developers.helpshift.com

If you want to customise themes for activities we now have a new theming solution from version 3.7.0 which is Gradle compatible. You can read more about it here -
https://developers.helpshift.com/android/design/#skinning

For future queries please email us at support@helpshift.com

Thanks,
Daniel

**Comment by danielvictor** [comment]
Hi,

Please refer to the documentation for the Helpshift Android SDK found here -
https://developers.helpshift.com

If you want to customise themes for activities we now have a new theming solution from version 3.7.0 which is Gradle compatible. You can read more about it here -
https://developers.helpshift.com/android/design/#skinning

For future queries please email us at support@helpshift.com

Thanks,
Daniel
