### ISSUE TITLE
Customising Helpshift ActionBar theme in Android Studio Gradle

### ISSUE THREAD

**Issue by BharathMG** [danielvictor/helpshift-android-sdk-examples#7]
Hi,

All your examples and tutorials about Theme customization assumes Eclipse environment where you ask us to change the Theme color inside YOUR SDK res folder which is NOT POSSIBLE in gradle (aar). Do you have any example GRADLE app which does theme customization? And also it is really not a nice way to do theme customization where we have to edit your theme folder. Android Studio completely disagrees with this. Very simple use case. Please reply.

**Comment by BharathMG** [comment]
And also ALL your github android sdk examples simply ignores the instructions in your tutorials. For ex,
you ask us to extend the "Helpshift.Theme.Base" from the app theme in the app styles.xml. BUT, this is not at all used in your examples. Ref : https://github.com/danielvictor/helpshift-android-sdk-examples/blob/master/HSThemeApp/res/values/styles_example.xml

**Comment by danielvictor** [comment]
Hi,

Please refer to the documentation for the Helpshift Android SDK found here -
https://developers.helpshift.com

If you want to customise themes for activities we now have a new theming solution from version 3.7.0 which is Gradle compatible. You can read more about it here -
https://developers.helpshift.com/android/design/#skinning

For future queries please email us at support@helpshift.com

Thanks,
Daniel
