### ISSUE TITLE
java.lang.NoClassDefFoundError: com.helpshift.Helpshift

### ISSUE THREAD

**Issue by yaxinhoo** [danielvictor/helpshift-android-sdk-examples#8]
04-06 21:59:40.232: E/AndroidRuntime(8136): FATAL EXCEPTION: main
04-06 21:59:40.232: E/AndroidRuntime(8136): java.lang.NoClassDefFoundError: com.helpshift.Helpshift
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at com.example.helpshiftdemo.HelpshiftDemoActivity.onCreate(HelpshiftDemoActivity.java:29)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at android.app.Activity.performCreate(Activity.java:5125)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2289)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2377)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at android.app.ActivityThread.access$600(ActivityThread.java:167)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at android.os.Looper.loop(Looper.java:153)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at android.app.ActivityThread.main(ActivityThread.java:5341)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at java.lang.reflect.Method.invoke(Method.java:511)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:929)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
04-06 21:59:40.232: E/AndroidRuntime(8136): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by danielvictor** [comment]
Hi,

Please send all support queries to support@helpshift.com so we can monitor and answer them in a timely fashion to avoid delays.
